FROM python:3.13.5

WORKDIR /app/

COPY ./judge/master/ .

RUN pip install -r requirements.txt

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

RUN chmod +x ./docker.sh

CMD [ "./docker.sh" ]