FROM python:3.13.5

WORKDIR /worker/

COPY ./judge/worker/ .

RUN pip install -r requirements.txt

RUN apt update && apt install curl adduser gcc g++ 

RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/isolate.asc] http://www.ucw.cz/isolate/debian/ bookworm-isolate main" > /etc/apt/sources.list

RUN curl https://www.ucw.cz/isolate/debian/signing-key.asc > /etc/apt/keyrings/isolate.asc

RUN apt update && apt install isolate

CMD [ "python", "main.py" ]
