# Generated by Django 5.2.4 on 2025-07-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('cpp', 'cpp'), ('python', 'python')])),
                ('input', models.TextField()),
                ('exp_result', models.TextField()),
                ('output', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('src', models.TextField()),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('setLimit', models.CharField(default='no')),
                ('timeLimit', models.IntegerField(default=3)),
                ('memoryLimit', models.IntegerField(default=256000)),
            ],
        ),
    ]
