# Generated by Django 5.2.4 on 2025-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='memoryLimit',
            new_name='memLimit',
        ),
    ]
