# Generated by Django 5.2.4 on 2025-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_memorylimit_submission_memlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='submitted', max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
